---

ansible_python_interpreter   : /usr/bin/python2
ansible_password : !vault |
          $ANSIBLE_VAULT;1.1;AES256
          62316235346535343432373430636130336335643130333464363664326230383963636439626163
          3737363333356566396631323631636361336462333638300a613835616464373762376331346435
          61643936393639653432383562386134613031613632393433616462636237623636646363366165
          3663343738633239350a396535616535383233616466346365353735663530343066643735363936
          6634

ansible_user : Administrator
ansible_port : 5986
ansible_connection: winrm
ansible_winrm_server_cert_validation : ignore
ansible_winrm_transport : basic
