---
- hosts: all
  become: false
  vars:
          src_f: /home/alex/EBO/
          dest_f: C:\Install\EBO\
          symbol: \ 
          files:
                  - Kapsch_BLR_EBO2TI_Installation.zip
                  - Kapsch_BLR_MIV_Installation.zip
          services: 
                  - Kapsch Contract Autotask Service
                  - Kapsch EBO2TI DataCollector Service
                  - Kapsch SttTransfer Autotask Service
                  - Kapsch EVignette Autotask Service
                  - Kapsch ExportDelictLetter Autotask Service
                  - Kapsch State Bodies Notification Service  
          iis:
                  - CboProxy
                  - Default Web Site
          appl:
                  - Kapsch_BLR_EBO2TI_Installation.exe
                  - Kapsch_BLR_MIV_Installation.exe
                     
  vars_prompt:
          - name: folder
            prompt: Enter folder name on ACC server
            private: no
          - name: srcfolder
            prompt: Enter source  folder for copying
            private: no

  tasks:
          - name: Create installation folder on ACC server
            win_file:
                    path: C:\Install\EBO\{{ folder }}
                    state: directory
          - block:
                  - name: Copy installation files
                    win_copy:
                            src: "{{src_f}}{{srcfolder}}/"
                            dest: "{{dest_f}}{{folder}}"
                    with_fileglob: "/home/alex/EBO/{{ srcfolder }}/*"
                  - name: Unzip installation files
                    win_unzip:
                            src: "{{dest_f}}{{folder}}{{symbol}}{{ item }}"
                            dest: "{{dest_f}}{{folder}}" 
                            remote_src: yes
                            delete_archive: yes
                            run_once: true
                    with_items: "{{files}}"
                  - name : Stop Kapsch Win services
                    win_service:
                            name: "{{ item }}"
                            state: stopped
                    with_items: "{{services}}"
                  - name: Check Win Services status
                    win_service:
                            name: "{{item}}"
                    with_items: "{{services}}"
                    register: r
                  - debug:
                          msg:
                                  - "----------------------------------------------------"
                                  - "Service={{item.display_name}} Status={{item.state}}"
                                  - "----------------------------------------------------"
                    with_items:
                            -  "{{r.results}}"
                  - name: Stop IIS
                    win_iis_website:
                            name: "{{item}}"
                            state: stopped
                    with_items: "{{iis}}"
                  - name: Install Kapsch appl's
                    win_command : "{{item}} /S /v/qn"
                    args:
                            chdir: "{{dest_f}}{{folder}}{{symbol}}"
                    with_items: "{{appl}}"
                  - name: Start IIS
                    win_iis_website:
                            name: "{{item}}"
                            state: started
                    with_items: "{{iis}}"
            ignore_errors: yes            
            when: inventory_hostname == "windows2012"      
          - block :
                  - name: Copy installation files for Citrix
                    win_copy:
                            src: "{{src_f}}{{srcfolder}}/Kapsch_BLR_MIV_Installation.zip"
                            dest: "{{dest_f}}{{folder}}/Kapsch_BLR_MIV_Installation.zip"
                  - name: Unzip MIV appl Citrix
                    win_unzip:
                            src: "{{dest_f}}{{folder}}/Kapsch_BLR_MIV_Installation.zip"
                            dest: "{{dest_f}}{{folder}}/"
                            remote_src: yes
                            delete_archive: yes
                  - name: Install MIV appl Citrix
                    win_command: "Kapsch_BLR_MIV_Installation.exe /S /v/qn"
                    args:
                            chdir : "{{dest_f}}{{folder}}{{symbol}}"
            when: inventory_hostname == "MIVAppl"

